package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"

	"github.com/The-Codefun-Exam-Team/GraphQL-Backend/graph/model"
)

// Submit is the resolver for the submit field.
func (r *mutationResolver) Submit(ctx context.Context, pcode string, code string) (*model.DebugSubmission, error) {
	panic(fmt.Errorf("not implemented: Submit - submit"))
}

// Newproblem is the resolver for the newproblem field.
func (r *mutationResolver) Newproblem(ctx context.Context, pcode *string, submissionid int) (model.NewProblemReturn, error) {
	panic(fmt.Errorf("not implemented: Newproblem - newproblem"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
